# schemas/persona_schema.py
from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Optional, Literal
import uuid


# ---------------------------------------------------------------------------
# UI Analysis — produced by Supervisor before persona generation
# ---------------------------------------------------------------------------

class InteractiveElement(BaseModel):
    """A single interactive element found in the HTML."""
    tag: str = Field(..., description="HTML tag, e.g. 'button', 'input', 'a', 'select'")
    selector: str = Field(..., description="Best CSS selector to target this element")
    label: Optional[str] = Field(None, description="Visible text, aria-label, or placeholder")
    input_type: Optional[str] = Field(None, description="For inputs: text | password | email | checkbox | etc.")
    is_accessible: bool = Field(True, description="Whether it has an accessible label/role")
    notes: Optional[str] = Field(None, description="Anything notable: missing label, no focus style, etc.")
    computed_styles: Optional[dict[str, str]] = Field(None, description="Computed CSS properties like color, backgroundColor, etc.")


class CriticalPath(BaseModel):
    """A key user workflow identified in the UI."""
    path_id: str
    name: str = Field(..., description="e.g. 'Login flow', 'Checkout', 'Form submission'")
    steps: list[str] = Field(..., description="Ordered list of steps in this workflow")
    accessibility_sensitive: bool = Field(
        False,
        description="True if this path involves forms, auth, navigation, or payment"
    )
    entry_selector: Optional[str] = Field(None, description="CSS selector of the first element in path")


class UIAnalysis(BaseModel):
    """
    Structured analysis of the HTML produced by the Supervisor Agent.
    Intermediate object — drives persona generation and passed as context to recommenders.
    """
    ui_purpose: str = Field(..., description="Inferred purpose of this UI")
    ui_type: str = Field(
        ...,
        description="e.g. 'login form', 'e-commerce product page', 'dashboard', 'landing page'"
    )
    critical_paths: list[CriticalPath]
    interactive_elements: list[InteractiveElement]
    detected_issues_hint: list[str] = Field(
        default_factory=list,
        description="Static observations: missing labels, no alt text, suspicious low-contrast elements, etc."
    )
    accessibility_risk_level: Literal["low", "medium", "high"] = Field(
        ...,
        description="Overall a11y risk based on static HTML analysis"
    )

    model_config = {"use_enum_values": True}


# ---------------------------------------------------------------------------
# Persona Profile
# ---------------------------------------------------------------------------

TechnicalSkill    = Literal["low", "medium", "high"]
RiskTolerance     = Literal["low", "medium", "high"]
LatencyTolerance  = Literal["low", "medium", "high"]
InteractionStyle  = Literal["methodical", "impatient", "exploratory", "cautious"]


class PersonaProfile(BaseModel):
    """
    Defines a simulated user persona.
    Generated by the Supervisor Agent and consumed by Persona Agents.
    """
    persona_id: str = Field(
        default_factory=lambda: f"persona_{uuid.uuid4().hex[:6]}",
        description="Unique identifier"
    )
    name: str = Field(..., description="Short descriptive name, e.g. 'Elderly screen reader user'")

    # Demographics & skill
    age_range: str = Field(..., description="e.g. '60-75'")
    technical_skill: TechnicalSkill

    # Accessibility & cognitive profile
    accessibility_constraints: list[str] = Field(
        default_factory=list,
        description="e.g. ['uses screen reader', 'colorblind', 'keyboard-only navigation']"
    )
    cognitive_limitations: list[str] = Field(
        default_factory=list,
        description="e.g. ['short attention span', 'low literacy', 'first-time user of this type of UI']"
    )

    # Task definition
    task_goal: str = Field(
        ...,
        description="Specific, actionable goal: what this persona is trying to accomplish on the UI"
    )
    task_context: str = Field(
        ...,
        description="Motivation and prior context — why this persona arrived at the UI"
    )
    entry_point: Optional[str] = Field(
        None,
        description="CSS selector where the persona starts interacting. None = top of page."
    )
    success_criteria: list[str] = Field(
        ...,
        description="Concrete observable conditions that confirm the task is complete"
    )

    # Why the supervisor generated this persona
    selection_rationale: str = Field(
        "",
        description=(
            "Supervisor's reasoning for including this persona: which UI risk or coverage gap "
            "it addresses, and why this specific profile (skill level, constraints, goal) "
            "was chosen over alternatives."
        )
    )

    # Behavioral profile
    risk_tolerance: RiskTolerance = "medium"
    latency_tolerance: LatencyTolerance = "medium"
    interaction_style: InteractionStyle = "methodical"

    model_config = {"use_enum_values": True}